version: '3.8'

services:
  test:
    build: .
    container_name: llm-prompt-regression-test
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./reports:/app/reports
    command: ["pytest", "tests/", "-v", "--cov=src"]
