test_name: "Basic Model Comparison Test"
description: "Basic test comparing GPT-3.5-turbo and GPT-4 responses"

prompts:
  - "Explain quantum computing in simple terms."
  - "Write a haiku about artificial intelligence."
  - "What are the benefits of renewable energy?"
  - "Describe the process of photosynthesis."
  - "Explain the difference between machine learning and deep learning."

models:
  - name: "gpt-3.5-turbo"
    model_type: "gpt-3.5-turbo"
    parameters:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 200
    description: "GPT-3.5 Turbo for baseline comparison"
    
  - name: "gpt-4"
    model_type: "gpt-4"
    parameters:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 200
    description: "GPT-4 for comparison testing"

parameter_variations:
  - temperature: 0.0
    description: "Deterministic responses"
  - temperature: 1.0
    description: "Creative responses"

max_retries: 3
request_timeout: 30
batch_size: 5
output_dir: "./reports"
