suite_name: "Comprehensive LLM Regression Test Suite"
description: "Complete test suite for LLM prompt regression testing"

tests:
  - test_name: "Basic Functionality Test"
    description: "Test basic model functionality and consistency"
    prompts:
      - "Hello, how are you?"
      - "What is 2+2?"
      - "Write a simple greeting."
    
    models:
      - name: "gpt-3.5-turbo"
        model_type: "gpt-3.5-turbo"
        parameters:
          temperature: 0.7
          max_tokens: 50
      - name: "gpt-4"
        model_type: "gpt-4"
        parameters:
          temperature: 0.7
          max_tokens: 50
    
    parameter_variations: []
    max_retries: 3
    request_timeout: 30
    batch_size: 5

  - test_name: "Temperature Sensitivity Test"
    description: "Test how temperature affects output consistency"
    prompts:
      - "Write a haiku about technology."
      - "Explain photosynthesis in one sentence."
      - "Describe the color blue."
    
    models:
      - name: "gpt-3.5-turbo"
        model_type: "gpt-3.5-turbo"
        parameters:
          temperature: 0.7
          max_tokens: 100
    
    parameter_variations:
      - temperature: 0.0
        description: "Deterministic"
      - temperature: 0.3
        description: "Conservative"
      - temperature: 1.0
        description: "Creative"
      - temperature: 1.5
        description: "Very Creative"
    
    max_retries: 3
    request_timeout: 30
    batch_size: 4

  - test_name: "Response Length Test"
    description: "Test how max_tokens affects response length"
    prompts:
      - "Write a detailed explanation of machine learning."
      - "Describe the process of making coffee."
      - "Explain the water cycle."
    
    models:
      - name: "gpt-3.5-turbo"
        model_type: "gpt-3.5-turbo"
        parameters:
          temperature: 0.7
    
    parameter_variations:
      - max_tokens: 50
        description: "Very Short"
      - max_tokens: 100
        description: "Short"
      - max_tokens: 200
        description: "Medium"
      - max_tokens: 400
        description: "Long"
    
    max_retries: 3
    request_timeout: 30
    batch_size: 4

  - test_name: "Model Comparison Test"
    description: "Compare different models on the same prompts"
    prompts:
      - "Explain quantum computing in simple terms."
      - "Write a creative story about AI."
      - "Compare renewable vs non-renewable energy."
      - "Describe the benefits of exercise."
      - "Explain the concept of democracy."
    
    models:
      - name: "gpt-3.5-turbo"
        model_type: "gpt-3.5-turbo"
        parameters:
          temperature: 0.7
          max_tokens: 200
      - name: "gpt-4"
        model_type: "gpt-4"
        parameters:
          temperature: 0.7
          max_tokens: 200
    
    parameter_variations:
      - temperature: 0.0
        description: "Deterministic comparison"
      - temperature: 1.0
        description: "Creative comparison"
    
    max_retries: 3
    request_timeout: 30
    batch_size: 5

global_settings:
  output_dir: "./reports"
  log_level: "INFO"
  ci_mode: false
