test_name: "Parameter Variation Test"
description: "Comprehensive test of different model parameters"

prompts:
  - "Write a creative story about a robot learning to paint."
  - "Explain the concept of machine learning to a 10-year-old."
  - "Describe the future of artificial intelligence in healthcare."
  - "Compare and contrast supervised vs unsupervised learning."
  - "Write a technical explanation of neural networks."

models:
  - name: "gpt-3.5-turbo"
    model_type: "gpt-3.5-turbo"
    parameters:
      temperature: 0.7
      top_p: 1.0
      max_tokens: 300
    description: "Base model for parameter testing"

parameter_variations:
  # Temperature variations
  - temperature: 0.0
    description: "Temperature 0.0 - Deterministic"
  - temperature: 0.3
    description: "Temperature 0.3 - Conservative"
  - temperature: 0.7
    description: "Temperature 0.7 - Balanced"
  - temperature: 1.0
    description: "Temperature 1.0 - Creative"
  - temperature: 1.5
    description: "Temperature 1.5 - Very Creative"
    
  # Top-p variations
  - top_p: 0.1
    description: "Top-p 0.1 - Very Focused"
  - top_p: 0.5
    description: "Top-p 0.5 - Focused"
  - top_p: 0.9
    description: "Top-p 0.9 - Diverse"
  - top_p: 1.0
    description: "Top-p 1.0 - Maximum Diversity"
  
  # Max tokens variations
  - max_tokens: 50
    description: "Max tokens 50 - Very Short"
  - max_tokens: 100
    description: "Max tokens 100 - Short"
  - max_tokens: 200
    description: "Max tokens 200 - Medium"
  - max_tokens: 500
    description: "Max tokens 500 - Long"
  
  # Combined variations
  - temperature: 0.0
    top_p: 0.5
    max_tokens: 100
    description: "Conservative + Focused + Short"
  - temperature: 1.0
    top_p: 1.0
    max_tokens: 300
    description: "Creative + Diverse + Long"

max_retries: 3
request_timeout: 30
batch_size: 3  # Smaller batch size due to many variations
output_dir: "./reports"
