name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'

jobs:
  # Combined lint and test job
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov
        pip install openai pydantic pyyaml python-dotenv tiktoken numpy scikit-learn
        pip install langchain langchain-openai matplotlib jinja2 seaborn plotly
        
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        flags: tests
        name: codecov-coverage
  
  # Real LLM integration test with actual OpenAI API
  # Only runs when PR is merged to main branch
  llm-regression-test:
    name: Real LLM Test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'skip-llm')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify API key
      run: python examples/test_openai_key.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Run real LLM test
      run: python examples/run_basic_test.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: llm-test-reports
        path: reports/
        retention-days: 7
  
  # Optional: Docker build test - demonstrates Docker usage
  # Note: Tests use mocked API calls, no real API key needed
  docker-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t llm-prompt-regression:test .
      
    - name: Run tests in Docker
      run: docker run --rm llm-prompt-regression:test
