name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Also publish this release to PyPI'
        required: false
        default: false
        type: boolean

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-release:
    name: Build and Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package (sdist + wheel)
        run: python -m build

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI (manual opt-in)
        if: github.event_name == 'workflow_dispatch' && inputs.publish_to_pypi == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist
          skip_existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}
